# # Javascript Node CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-javascript/ for more details
# #

version: 2
aliases:
  - &restore-cache
    keys:
      - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      - v1-dependencies-{{ .Branch }}

  - &save-node-cache
    key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &save-ios-cache
    key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules
      - ios/build

  - &install-node-dependencies
    name: Install node dependencies
    command: yarn install

defaults: &defaults
  working_directory: ~/kancha-ui

jobs:
  # e2e tests with detox
  test-ios-e2e:
    <<: *defaults
    macos:
      xcode: '10.2.1'
      pre:
    steps:
      - checkout
      - run:
          name: Install AppleSim Utils
          command: |
            brew update
            brew tap wix/brew
            brew install --HEAD applesimutils
      - run:
          name: Install Detox CLI
          command: npm install -g detox-cli
      - run: *install-node-dependencies
      - run:
          name: Compile TypeScript
          command: yarn build
      - run:
          name: Detox e2e build
          command: detox build -c ios.sim.release
      - run:
          name: Detox e2e test
          command: detox test -c ios.sim.release --cleanup

  # unit tests
  test-js:
    <<: *defaults
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-node-dependencies
      - save_cache: *save-ios-cache
      - run: yarn test

  # publish to npm
  publish-npm:
    <<: *defaults
    branches:
      only:
        - master
        - beta
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-node-dependencies
      - run:
          name: Release version to npm
          command: yarn semantic-release

workflows:
  version: 2

  unit-ios-e2e:
    jobs:
      - test-js
      - test-ios-e2e:
          requires:
            - test-js
      # To be enabled when a beta branch is created
      # - publish-npm:
      #     requires:
      #       - test-js
      #       - test-ios-e2e
