name: iOS

on: [push, pull_request]

jobs:
  test-ios-device-e2e:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        uses: actions/checkout@v1

      - name: Specify node version
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Detox setup
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Install node_modules & deploy with specific XCode version
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
        run: |
          yarn install --frozen-lockfile

      - name: Build typescript
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        run: yarn build

      - name: Compile test app
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        run: npx detox build -c ios.sim.release

      - name: iOS test
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        run: |
          npx detox clean-framework-cache && npx detox build-framework-cache
          npx detox test -c ios.sim.release --cleanup
